// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwzvgwijyqkhkoecrnsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3enZnd2lqeXFraGtvZWNybnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwMjk4MjIsImV4cCI6MjA1MjYwNTgyMn0.K8119FVDVehbLgR6bjCIKOuPUUDFhFUI46AwJO638RI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);